const fs = require('fs');

// 1. Update Translations
const trPath = 'src/locales/tr/translation.json';
const enPath = 'src/locales/en/translation.json';

const trData = JSON.parse(fs.readFileSync(trPath, 'utf8'));
const enData = JSON.parse(fs.readFileSync(enPath, 'utf8'));

trData.predictive = {
    "urg_critical": "Kritik",
    "urg_warning": "Yaklaşıyor",
    "urg_soon": "Planla",
    "urg_ok": "İyi Durumda",

    "risk_high": "Yüksek Risk",
    "risk_med": "Orta Risk",
    "risk_low": "Düşük Risk",

    "ai_prompt_lang": "Türkçe",

    "unknown": "Bilinmiyor",
    "remaining_km": "~{{km}} kaldı",
    "confidence": "%{{score}} güven",
    "last_service": "Son bakım",
    "schedule_btn": "Randevu Oluştur",

    "loading": "Veriler yükleniyor...",
    "title": "Bakım Tahmini",
    "subtitle": "AI destekli öngörülü bakım analizi",

    "ai_analyzing": "AI analiz ediyor...",
    "ai_processing": "Servis geçmişi ve araç verileri işleniyor",
    "ai_evaluation": "AI Değerlendirmesi",

    "filter_all": "Tümü",
    "filter_critical_short": "Kritik",
    "filter_warning_short": "Yakında",
    "filter_soon_short": "Planla",
    "filter_ok_short": "İyi",

    "refresh": "Analizi Yenile",
    "not_found": "Araç bulunamadı.",
    "add_vehicle": "Araç Ekle",
    "info_note": "Tahminler servis geçmişiniz ve araç verilerinize dayalı AI analiziyle oluşturulur. Gerçek değerler aracınızın kullanım koşullarına göre farklılık gösterebilir."
};

enData.predictive = {
    "urg_critical": "Critical",
    "urg_warning": "Warning",
    "urg_soon": "Plan Soon",
    "urg_ok": "Good",

    "risk_high": "High Risk",
    "risk_med": "Medium Risk",
    "risk_low": "Low Risk",

    "ai_prompt_lang": "English",

    "unknown": "Unknown",
    "remaining_km": "~{{km}} left",
    "confidence": "{{score}}% confidence",
    "last_service": "Last service",
    "schedule_btn": "Schedule",

    "loading": "Loading data...",
    "title": "Predictive Maintenance",
    "subtitle": "AI-powered predictive maintenance analysis",

    "ai_analyzing": "AI is analyzing...",
    "ai_processing": "Processing service history and vehicle data",
    "ai_evaluation": "AI Evaluation",

    "filter_all": "All",
    "filter_critical_short": "Critical",
    "filter_warning_short": "Upcoming",
    "filter_soon_short": "Plan",
    "filter_ok_short": "Good",

    "refresh": "Refresh Analysis",
    "not_found": "Vehicle not found.",
    "add_vehicle": "Add Vehicle",
    "info_note": "Predictions are generated by AI analysis based on your service history and vehicle data. Actual values may vary depending on your vehicle's usage conditions."
};

fs.writeFileSync(trPath, JSON.stringify(trData, null, 4));
fs.writeFileSync(enPath, JSON.stringify(enData, null, 4));

// 2. Update code
let content = fs.readFileSync('pages/PredictiveMaintenance.tsx', 'utf8');

if (!content.includes('import { useTranslation }')) {
    content = content.replace(
        "import { useNavigate } from 'react-router-dom';",
        "import { useNavigate } from 'react-router-dom';\nimport { useTranslation } from 'react-i18next';"
    );
}

// Pass language to AI prompt
content = content.replace(
    "const getPredictiveMaintenance = async (\n  vehicle: Vehicle, \n  logs: ServiceLog[]\n): Promise<AIPredictionResult | null> => {",
    "const getPredictiveMaintenance = async (\n  vehicle: Vehicle, \n  logs: ServiceLog[],\n  lang: string\n): Promise<AIPredictionResult | null> => {"
);
// replace response language in prompt
content = content.replace(
    "1-2 cümle genel değerlendirme (Türkçe)",
    "1-2 cümle genel değerlendirme (${lang})"
);
content = content.replace(
    "kısa Türkçe açıklama",
    "kısa ${lang} açıklama"
);

// We need to provide t to ConfidenceBadge, PredictionCard, RiskMeter, or use strings directly if they are outside scope.
// But they can be passed as props. Or we can just use `<Translation>` or `t` inside them by calling hook.
content = content.replace(
    "const ConfidenceBadge: React.FC<{ confidence: number }> = ({ confidence }) => {",
    "const ConfidenceBadge: React.FC<{ confidence: number }> = ({ confidence }) => {\n  const { t } = useTranslation();"
);
content = content.replace("<span>%{confidence} güven</span>", "<span>{t('predictive.confidence', { score: confidence })}</span>");

content = content.replace(
    "const PredictionCard: React.FC<{ \n  prediction: MaintenancePrediction; \n  onSchedule: (item: string) => void \n}> = ({ prediction, onSchedule }) => {",
    "const PredictionCard: React.FC<{ \n  prediction: MaintenancePrediction; \n  onSchedule: (item: string) => void \n}> = ({ prediction, onSchedule }) => {\n  const { t } = useTranslation();"
);
// Inside PredictionCard
content = content.replace(
    "const cfg = URGENCY_CONFIG[urgency];",
    "const cfg = URGENCY_CONFIG[urgency];\n  const urgencyLabels: Record<string, string> = { critical: t('predictive.urg_critical'), warning: t('predictive.urg_warning'), soon: t('predictive.urg_soon'), ok: t('predictive.urg_ok') };"
);
content = content.replace("{cfg.label}", "{urgencyLabels[urgency]}");
content = content.replace("<span>Son bakım</span>", "<span>{t('predictive.last_service')}</span>");
content = content.replace("? formatKm(lastDoneKm) : 'Bilinmiyor'", "? formatKm(lastDoneKm) : t('predictive.unknown')");
content = content.replace("<span>~{formatKm(kmRemaining)} kaldı</span>", "<span>{t('predictive.remaining_km', { km: formatKm(kmRemaining) })}</span>");
content = content.replace("Randevu Oluştur", "{t('predictive.schedule_btn')}");

content = content.replace(
    "const RiskMeter: React.FC<{ risk: 'Yüksek' | 'Orta' | 'Düşük' | null }> = ({ risk }) => {",
    "const RiskMeter: React.FC<{ risk: 'Yüksek' | 'Orta' | 'Düşük' | null }> = ({ risk }) => {\n  const { t } = useTranslation();\n  const riskLabels: Record<string, string> = { 'Yüksek': t('predictive.risk_high'), 'Orta': t('predictive.risk_med'), 'Düşük': t('predictive.risk_low') };"
);
content = content.replace("{c.label}", "{riskLabels[risk] || risk}");

// Main Component
content = content.replace(
    "export const PredictiveMaintenance: React.FC = () => {\n  const navigate = useNavigate();",
    "export const PredictiveMaintenance: React.FC = () => {\n  const navigate = useNavigate();\n  const { t } = useTranslation();"
);
content = content.replace(
    "const result = await getPredictiveMaintenance(selectedVehicle, logs);",
    "const result = await getPredictiveMaintenance(selectedVehicle, logs, t('predictive.ai_prompt_lang'));"
);

// Filter chips array map
content = content.replace(
    "{([",
    "{([\n              { key: 'all', label: t('predictive.filter_all') },\n              { key: 'critical', label: `🔴 ${t('predictive.filter_critical_short')}` },\n              { key: 'warning', label: `🟡 ${t('predictive.filter_warning_short')}` },\n              { key: 'soon', label: `🔵 ${t('predictive.filter_soon_short')}` },\n              { key: 'ok', label: `🟢 ${t('predictive.filter_ok_short')}` },\n            ] as const).map(({ key, label }) => (\n              <button"
);
content = content.replace(
    "              { key: 'all', label: 'Tümü' },\n              { key: 'critical', label: '🔴 Kritik' },\n              { key: 'warning', label: '🟡 Yakında' },\n              { key: 'soon', label: '🔵 Planla' },\n              { key: 'ok', label: '🟢 İyi' },\n            ] as const).map(({ key, label }) => (\n              <button",
    ""
);

// Grid filters array map
content = content.replace(
    "            {[\n              { key: 'critical', label: 'Kritik',    color: 'text-red-400',     bg: 'bg-red-500/10',     border: 'border-red-500/20'     },\n              { key: 'warning',  label: 'Yakında',   color: 'text-amber-400',   bg: 'bg-amber-500/10',   border: 'border-amber-500/20'   },\n              { key: 'soon',     label: 'Planla',    color: 'text-blue-400',    bg: 'bg-blue-500/10',    border: 'border-blue-500/20'    },\n              { key: 'ok',       label: 'İyi',       color: 'text-emerald-400', bg: 'bg-emerald-500/10', border: 'border-emerald-500/20' },\n            ].map",
    "            {[\n              { key: 'critical', label: t('predictive.filter_critical_short'), color: 'text-red-400',     bg: 'bg-red-500/10',     border: 'border-red-500/20'     },\n              { key: 'warning',  label: t('predictive.filter_warning_short'), color: 'text-amber-400',   bg: 'bg-amber-500/10',   border: 'border-amber-500/20'   },\n              { key: 'soon',     label: t('predictive.filter_soon_short'), color: 'text-blue-400',    bg: 'bg-blue-500/10',    border: 'border-blue-500/20'    },\n              { key: 'ok',       label: t('predictive.filter_ok_short'), color: 'text-emerald-400', bg: 'bg-emerald-500/10', border: 'border-emerald-500/20' },\n            ].map"
);

// UI text
const rep = [
    [">Veriler yükleniyor...<", ">{t('predictive.loading')}<"],
    [">Bakım Tahmini<", ">{t('predictive.title')}<"],
    [">AI destekli öngörülü bakım analizi<", ">{t('predictive.subtitle')}<"],
    [">AI analiz ediyor...<", ">{t('predictive.ai_analyzing')}<"],
    [">Servis geçmişi ve araç verileri işleniyor<", ">{t('predictive.ai_processing')}<"],
    [">AI Değerlendirmesi<", ">{t('predictive.ai_evaluation')}<"],
    [">Analizi Yenile<", ">{t('predictive.refresh')}<"],
    [">Araç bulunamadı.<", ">{t('predictive.not_found')}<"],
    [">Araç Ekle<", ">{t('predictive.add_vehicle')}<"],
    [">Tahminler servis geçmişiniz ve araç verilerinize dayalı AI analiziyle oluşturulur. Gerçek değerler aracınızın kullanım koşullarına göre farklılık gösterebilir.<", ">{t('predictive.info_note')}<"]
];

for (const [s, r] of rep) {
    if (content.includes(s)) {
        content = content.split(s).join(r);
    }
}

fs.writeFileSync('pages/PredictiveMaintenance.tsx', content);
console.log('PredictiveMaintenance translated!');
