const fs = require('fs');
const path = require('path');

const trPath = path.join(__dirname, 'src', 'locales', 'tr', 'translation.json');
const enPath = path.join(__dirname, 'src', 'locales', 'en', 'translation.json');

const tr = JSON.parse(fs.readFileSync(trPath, 'utf8'));
const en = JSON.parse(fs.readFileSync(enPath, 'utf8'));

// Dictionaries
const dictTR = {
    // Premium
    "prem.title": "CarSync Premium",
    "prem.desc": "Araç yönetiminde tüm sınırları kaldır, profesyonel özelliklere eriş.",
    "prem.trusted_by": "kullanıcı güveniyor",
    "prem.monthly": "Aylık",
    "prem.yearly": "Yıllık",
    "prem.discount": "%{{pct}} İndirim",
    "prem.save_yearly": "Yıllık planla ₺{{amount}} tasarruf edersin",
    "prem.per_year": "/yıl",
    "prem.per_month": "/ay",
    "prem.yearly_desc": "Aylık ₺{{amt}}'ye geliyor · Tek seferlik ödeme",
    "prem.monthly_desc": "İstediğin zaman iptal et · Taahhüt yok",
    "prem.refund_notice": "7 gün içinde memnun kalmazsan <1>tam iade</1>",
    "prem.compare_title": "Ücretsiz vs Premium",
    "prem.feature": "Özellik",
    "prem.free": "Ücretsiz",
    "prem.premium": "Premium",
    "prem.feat1": "Araç sayısı", "prem.feat1_free": "2 araç", "prem.feat1_pro": "Sınırsız",
    "prem.feat2": "Servis kaydı", "prem.feat2_free": "50 kayıt", "prem.feat2_pro": "Sınırsız",
    "prem.feat3": "AI fatura analizi", "prem.feat3_free": "3/ay", "prem.feat3_pro": "Sınırsız",
    "prem.feat4": "Araç karşılaştırma",
    "prem.feat5": "CSV / PDF dışa aktarım",
    "prem.feat6": "Gelişmiş analitik",
    "prem.feat7": "Reklamsız deneyim",
    "prem.feat8": "Öncelikli destek",
    "prem.testimonial": "Yakıt masraflarımı takip etmek çok kolaylaştı. Bir ayda ₺800 tasarruf ettim!",
    "prem.user_name": "Mehmet Y.",
    "prem.user_desc": "2 araç sahibi · 8 ay Premium kullanıcısı",
    "prem.badge_refund": "7 Gün\\nİade",
    "prem.badge_ssl": "SSL\\nGüvenli",
    "prem.badge_users": "12.000+\\nKullanıcı",
    "prem.processing": "İşleniyor...",
    "prem.already_active": "Premium zaten aktif · Geri Dön",
    "prem.upgrade_btn_year": "₺{{amt}}/yıl ile Premium'a Geç",
    "prem.upgrade_btn_month": "₺{{amt}}/ay ile Premium'a Geç",
    "prem.terms": "Devam ederek Kullanım Koşulları ve Gizlilik Politikası'nı kabul etmiş olursunuz.",
    "prem.active_plan": "Aktif Plan",

    // ServiceAppointment
    "appt.upcoming": "Yaklaşıyor",
    "appt.today_alert": "Bugün!",
    "appt.overdue": "Gecikmiş",
    "appt.completed": "Tamamlandı",
    "appt.modal_edit": "Randevuyu Düzenle",
    "appt.modal_new": "Randevu Oluştur",
    "appt.car": "Araç",
    "appt.service_type": "Servis Türü",
    "appt.est_cost": "Tahmini maliyet:",
    "appt.date": "Randevu Tarihi",
    "appt.location": "Servis/Konum",
    "appt.location_ph": "Oto Servis İsmi",
    "appt.phone": "Telefon",
    "appt.phone_ph": "0212 000 00 00",
    "appt.reminder": "Hatırlatma:",
    "appt.days_before": "{{days}} gün önce",
    "appt.notes": "Not",
    "appt.notes_ph": "Özel talepler, araç anahtarı bırakma saati...",
    "appt.btn_update": "Güncelle",
    "appt.btn_create": "Randevu Oluştur",
    "appt.status_completed_label": "Tamamlandı",
    "appt.days_overdue": "{{days}} gün gecikmiş",
    "appt.tomorrow": "Yarın",
    "appt.days_left": "{{days}} gün kaldı",
    "appt.reminder_active": "Hatırlatma aktif — {{days}} gün kaldı",
    "appt.loading": "Randevular yükleniyor...",
    "appt.title": "Servis Randevuları",
    "appt.subtitle": "Planlama ve hatırlatma takvimi",
    "appt.filter_active": "Aktif ({{count}})",
    "appt.filter_completed": "Tamamlandı",
    "appt.filter_all": "Tümü",
    "appt.alert_overdue": "{{count}} gecikmiş randevu var — hemen planla!",
    "appt.alert_today": "Bugün {{count}} randevunuz var!",
    "appt.stat_upcoming": "Yaklaşan",
    "appt.stat_overdue": "Gecikmiş",
    "appt.stat_today": "Bugün",
    "appt.no_appt": "Randevu Yok",
    "appt.no_appt_desc": "Servis, muayene veya bakım randevusu oluştur. Tarih yaklaşınca otomatik hatırlatma alırsın.",
    "appt.btn_first": "İlk Randevuyu Oluştur",
    "appt.legend_appt": "Randevu",
    "appt.legend_overdue": "Gecikmiş",
    "appt.legend_today": "Bugün",

    // Settings
    "settings.title": "Ayarlar",
    "settings.save": "Kaydet",
    "settings.upload_gallery": "Galeriden Seç",
    "settings.take_photo": "Fotoğraf Çek",
    "settings.badge_pro": "PRO",
    "settings.edit_profile": "Profili Düzenle",
    "settings.lbl_name": "İSİM",
    "settings.lbl_surname": "SOYİSİM",
    "settings.lbl_email": "E-POSTA",
    "settings.lbl_phone": "TELEFON",
    "settings.lbl_dept": "BÖLÜM / DEPARTMAN",
    "settings.ph_name": "İsim",
    "settings.ph_surname": "Soyisim",
    "settings.ph_email": "E-posta Adresi",
    "settings.ph_phone": "Telefon Numarası",
    "settings.ph_dept": "Örn: Muhasebe, İK, Satış...",
    "settings.cancel": "İptal",
    "settings.promo_features": "PRO ÖZELLİKLER",
    "settings.promo_title": "Premium'a Yükselt",
    "settings.promo_desc": "Sınırsız araç ekle, yapay zeka analizlerini kullan ve detaylı raporlara eriş.",
    "settings.promo_btn": "Hemen Başla",
    "settings.sec_general": "Genel",
    "settings.notifications": "Bildirimler",
    "settings.font_size": "Yazı Boyutu",
    "settings.font_small": "Küçük",
    "settings.font_medium": "Orta",
    "settings.font_large": "Büyük",
    "settings.bg_theme": "Arka Plan Teması",
    "settings.bg_default": "Varsayılan",
    "settings.bg_blue": "Mavi Ton",
    "settings.bg_mesh": "Mesh",
    "settings.reminders": "Hatırlatıcı Varsayılanları",
    "settings.dark_mode": "Karanlık Mod",
    "settings.sec_sub": "Abonelik",
    "settings.sub_title": "Abonelik & Premium",
    "settings.sub_active": "Aktif: Yıllık Plan",
    "settings.sub_free": "Ücretsiz Plan",
    "settings.sec_data": "Veri Yönetimi",
    "settings.csv_vehicles": "Araç Listesi (CSV)",
    "settings.csv_history": "Servis Geçmişi (CSV)",
    "settings.pdf_report": "Garaj Raporu (PDF)",
    "settings.archived": "Arşivlenmiş Araçlar",
    "settings.security": "Güvenlik",
    "settings.legal": "Hakkında & Yasal",
    "settings.logout": "Çıkış Yap",
    "settings.logout_confirm": "Çıkış yapmak istediğinize emin misiniz?",
    "settings.msg_saved": "Profil başarıyla güncellendi!",
    "settings.msg_err": "Profil güncellenirken bir hata oluştu.",
    "settings.reminders_saved": "Hatırlatıcı tercihleri kaydedildi.",
    "settings.notif_saved": "Bildirim tercihleri başarıyla kaydedildi.",
    "settings.notif_saved_full": "Ayarlar kaydedildi. \\\"Yaklaşan Servis\\\" ve \\\"Yakıt Uyarıları\\\" aktif!",
    "settings.pass_mismatch": "Yeni şifreler eşleşmiyor!",
    "settings.pass_short": "Şifre en az 6 karakter olmalıdır.",
    "settings.pass_success": "Şifreniz başarıyla güncellendi.",
    "settings.pass_err_wrong": "Mevcut şifre hatalı.",
    "settings.pass_err_general": "Şifre güncellenirken bir hata oluştu: ",
    "settings.sub_cancel_confirm": "Premium üyeliğinizi iptal etmek istediğinize emin misiniz? Premium özelliklere erişiminizi kaybedeceksiniz.",
    "settings.sub_cancelled": "Üyeliğiniz iptal edildi.",
    "settings.restore_confirm": "Araç başarıyla garajınıza geri yüklendi!\\n\\nGarajınıza gitmek ister misiniz?",
    "settings.lbl_archived_title": "Arşivlenmiş Araçlar",
    "settings.lbl_restore": "Geri Yükle",
    "settings.msg_no_archived": "Arşivlenmiş araç bulunmuyor.",
    "settings.prem_title": "Abonelik & Premium",
    "settings.prem_active_badge": "AKTİF PLAN",
    "settings.prem_plan_name": "CarSync Pro Yıllık",
    "settings.prem_all_active": "Tüm özellikler aktif",
    "settings.prem_renew": "Yenilenme: <1>12 Ekim 2024</1>",
    "settings.prem_payment": "Ödeme Yöntemi",
    "settings.prem_card_exp": "Mastercard - Sona erme 09/28",
    "settings.prem_change": "Değiştir",
    "settings.prem_active_feats": "Aktif Özellikler",
    "settings.feat_unlimited": "Sınırsız Araç Ekleme",
    "settings.feat_ai": "Gelişmiş AI Arıza Analizi",
    "settings.feat_reports": "Detaylı Filo Raporları",
    "settings.feat_no_ads": "Reklamsız Deneyim",
    "settings.feat_support": "Öncelikli Destek",
    "settings.prem_cancel": "Üyeliği İptal Et",
    "settings.prem_cancel_desc": "İptal ederseniz, fatura döneminizin sonuna kadar (12 Ekim 2024) özelliklerden yararlanmaya devam edebilirsiniz.",
    "settings.free_title": "Şu an Ücretsiz Plandasınız",
    "settings.free_desc": "CarSync Pro'nun tüm potansiyelini keşfetmek için yükseltin.",
    "settings.free_btn": "Planları İncele",
    "settings.free_missing": "Neler Kaçırıyorsunuz?",
    "settings.free_max2": "Maks 2 Araç",
    "settings.free_in_free": "Ücretsiz Planda",
    "settings.free_unlimited": "Sınırsız Araç",
    "settings.free_in_pro": "Premium Planda",
    "settings.free_ai": "Detaylı Yapay Zeka Analizi",
    "settings.free_ai_desc": "Arıza kodları ve faturalar için",
    "settings.free_rep": "Gelişmiş Raporlama",
    "settings.free_rep_desc": "PDF dökümü ve CSV çıktısı",
    "settings.free_ads": "Reklamsız Kullanım",
    "settings.free_ads_desc": "Tamamen temiz arayüz",
    "settings.legal_title": "Hakkında & Yasal",
    "settings.legal_version": "Sürüm 1.0.3 (Build 2024)",
    "settings.legal_desc": "Profesyonel araç yönetimi, bakım takibi ve yapay zeka destekli analiz uygulaması.",
    "settings.legal_texts": "Yasal Metinler",
    "settings.legal_privacy": "Gizlilik Politikası",
    "settings.legal_terms": "Kullanım Koşulları",
    "settings.legal_data": "Veri Kullanımı ve AI Servisleri",
    "settings.legal_data_desc": "CarSync Pro, fatura analizi ve araç arıza tahmini gibi özellikler sunmak için <1>Google Gemini API</1> kullanır.",
    "settings.rem_title": "Hatırlatıcı Ayarları",
    "settings.rem_desc": "Kayıt eklerken otomatik olarak önerilecek varsayılan bakım aralıklarını belirleyin.",
    "settings.rem_oil": "Yağ Değişimi",
    "settings.rem_every_km": "Her (km)",
    "settings.rem_every_mo": "Her (Ay)",
    "settings.notif_title": "Bildirim Tercihleri",
    "settings.notif_events": "Olay Bildirimleri",
    "settings.notif_maint": "Bakım Hatırlatmaları",
    "settings.notif_fuel": "Yakıt Tüketim Uyarıları",
    "settings.notif_ins": "Sigorta & Kasko",
    "settings.notif_tax": "Vergi (MTV) Ödemeleri",
    "settings.notif_dtc": "Kritik Arıza Bildirimleri",
    "settings.notif_news": "Kampanya ve Haberler",
    "settings.notif_channels": "İletişim Kanalları",
    "settings.notif_push": "Anlık Bildirimler",
    "settings.sec_title": "Güvenlik Ayarları",
    "settings.sec_change": "Şifre Değiştir",
    "settings.sec_cur": "Mevcut Şifre",
    "settings.sec_new": "Yeni Şifre",
    "settings.sec_confirm": "Yeni Şifre (Tekrar)",
    "settings.sec_update": "Şifreyi Güncelle",
    "settings.sec_2fa": "İki Faktörlü Doğrulama (2FA)",
    "settings.sec_sms": "SMS Doğrulama",
    "settings.sec_sms_desc": "Giriş yaparken telefonunuza kod gönderilir.",
    "settings.sec_2fa_active": "İki faktörlü doğrulama etkinleştirildi. Bir sonraki girişinizde kayıtlı telefon numaranıza doğrulama kodu gönderilecektir.",
    "settings.danger": "Tehlikeli Bölge",
    "settings.wipe": "Tüm Verileri Sil",
    "settings.wipe_modal_title": "Tüm Verileri Sil?",
    "settings.wipe_modal_desc": "Bu işlem <1>geri alınamaz</1>. Tüm araç kayıtlarınız, ayarlarınız ve geçmişiniz kalıcı olarak silinecektir. Uygulama başlangıç durumuna dönecektir.",
    "settings.wipe_yes": "Evet, Sil"
};

const dictEN = {
    // Premium
    "prem.title": "CarSync Premium",
    "prem.desc": "Remove all limits in vehicle management and access professional features.",
    "prem.trusted_by": "users trust us",
    "prem.monthly": "Monthly",
    "prem.yearly": "Yearly",
    "prem.discount": "{{pct}}% Off",
    "prem.save_yearly": "Save ₺{{amount}} with a yearly plan",
    "prem.per_year": "/year",
    "prem.per_month": "/mo",
    "prem.yearly_desc": "Comes to ₺{{amt}}/mo · One-time payment",
    "prem.monthly_desc": "Cancel anytime · No commitment",
    "prem.refund_notice": "Not satisfied? <1>Full refund</1> within 7 days",
    "prem.compare_title": "Free vs Premium",
    "prem.feature": "Feature",
    "prem.free": "Free",
    "prem.premium": "Premium",
    "prem.feat1": "Number of vehicles", "prem.feat1_free": "2 vehicles", "prem.feat1_pro": "Unlimited",
    "prem.feat2": "Service logs", "prem.feat2_free": "50 logs", "prem.feat2_pro": "Unlimited",
    "prem.feat3": "AI invoice analysis", "prem.feat3_free": "3/mo", "prem.feat3_pro": "Unlimited",
    "prem.feat4": "Vehicle comparison",
    "prem.feat5": "CSV / PDF export",
    "prem.feat6": "Advanced analytics",
    "prem.feat7": "Ad-free experience",
    "prem.feat8": "Priority support",
    "prem.testimonial": "Tracking fuel costs is now so easy. I saved ₺800 in a month!",
    "prem.user_name": "Mehmet Y.",
    "prem.user_desc": "2 vehicles · Premium user for 8 months",
    "prem.badge_refund": "7-Day\\nRefund",
    "prem.badge_ssl": "SSL\\nSecured",
    "prem.badge_users": "12,000+\\nUsers",
    "prem.processing": "Processing...",
    "prem.already_active": "Premium already active · Go Back",
    "prem.upgrade_btn_year": "Upgrade for ₺{{amt}}/year",
    "prem.upgrade_btn_month": "Upgrade for ₺{{amt}}/month",
    "prem.terms": "By continuing, you agree to our Terms of Use and Privacy Policy.",
    "prem.active_plan": "Active Plan",

    // ServiceAppointment
    "appt.upcoming": "Upcoming",
    "appt.today_alert": "Today!",
    "appt.overdue": "Overdue",
    "appt.completed": "Completed",
    "appt.modal_edit": "Edit Appointment",
    "appt.modal_new": "New Appointment",
    "appt.car": "Vehicle",
    "appt.service_type": "Service Type",
    "appt.est_cost": "Estimated cost:",
    "appt.date": "Appointment Date",
    "appt.location": "Service/Location",
    "appt.location_ph": "Auto Service Name",
    "appt.phone": "Phone",
    "appt.phone_ph": "0212 000 00 00",
    "appt.reminder": "Reminder:",
    "appt.days_before": "{{days}} days before",
    "appt.notes": "Notes",
    "appt.notes_ph": "Special requests, key drop-off time...",
    "appt.btn_update": "Update",
    "appt.btn_create": "Create Appointment",
    "appt.status_completed_label": "Completed",
    "appt.days_overdue": "{{days}} days overdue",
    "appt.tomorrow": "Tomorrow",
    "appt.days_left": "{{days}} days left",
    "appt.reminder_active": "Reminder active — {{days}} days left",
    "appt.loading": "Loading appointments...",
    "appt.title": "Service Appointments",
    "appt.subtitle": "Planning and reminder calendar",
    "appt.filter_active": "Active ({{count}})",
    "appt.filter_completed": "Completed",
    "appt.filter_all": "All",
    "appt.alert_overdue": "There are {{count}} overdue appointments — plan them now!",
    "appt.alert_today": "You have {{count}} appointments today!",
    "appt.stat_upcoming": "Upcoming",
    "appt.stat_overdue": "Overdue",
    "appt.stat_today": "Today",
    "appt.no_appt": "No Appointments",
    "appt.no_appt_desc": "Create a service, inspection or maintenance appointment. You will receive an automatic reminder when the date approaches.",
    "appt.btn_first": "Create First Appointment",
    "appt.legend_appt": "Appointment",
    "appt.legend_overdue": "Overdue",
    "appt.legend_today": "Today",

    // Settings
    "settings.title": "Settings",
    "settings.save": "Save",
    "settings.upload_gallery": "Upload from Gallery",
    "settings.take_photo": "Take Photo",
    "settings.badge_pro": "PRO",
    "settings.edit_profile": "Edit Profile",
    "settings.lbl_name": "NAME",
    "settings.lbl_surname": "SURNAME",
    "settings.lbl_email": "EMAIL",
    "settings.lbl_phone": "PHONE",
    "settings.lbl_dept": "DEPARTMENT",
    "settings.ph_name": "Name",
    "settings.ph_surname": "Surname",
    "settings.ph_email": "Email Address",
    "settings.ph_phone": "Phone Number",
    "settings.ph_dept": "e.g. Accounting, HR, Sales...",
    "settings.cancel": "Cancel",
    "settings.promo_features": "PRO FEATURES",
    "settings.promo_title": "Upgrade to Premium",
    "settings.promo_desc": "Add unlimited vehicles, use AI analysis, and access detailed reports.",
    "settings.promo_btn": "Get Started",
    "settings.sec_general": "General",
    "settings.notifications": "Notifications",
    "settings.font_size": "Font Size",
    "settings.font_small": "Small",
    "settings.font_medium": "Medium",
    "settings.font_large": "Large",
    "settings.bg_theme": "Background Theme",
    "settings.bg_default": "Default",
    "settings.bg_blue": "Blue Tone",
    "settings.bg_mesh": "Mesh",
    "settings.reminders": "Reminder Defaults",
    "settings.dark_mode": "Dark Mode",
    "settings.sec_sub": "Subscription",
    "settings.sub_title": "Subscription & Premium",
    "settings.sub_active": "Active: Yearly Plan",
    "settings.sub_free": "Free Plan",
    "settings.sec_data": "Data Management",
    "settings.csv_vehicles": "Vehicle List (CSV)",
    "settings.csv_history": "Service History (CSV)",
    "settings.pdf_report": "Garage Report (PDF)",
    "settings.archived": "Archived Vehicles",
    "settings.security": "Security",
    "settings.legal": "About & Legal",
    "settings.logout": "Logout",
    "settings.logout_confirm": "Are you sure you want to log out?",
    "settings.msg_saved": "Profile successfully updated!",
    "settings.msg_err": "An error occurred while updating the profile.",
    "settings.reminders_saved": "Reminder preferences saved.",
    "settings.notif_saved": "Notification preferences saved successfully.",
    "settings.notif_saved_full": "Settings saved. 'Upcoming Service' and 'Fuel Alerts' are active!",
    "settings.pass_mismatch": "New passwords do not match!",
    "settings.pass_short": "Password must be at least 6 characters.",
    "settings.pass_success": "Your password has been successfully updated.",
    "settings.pass_err_wrong": "Current password is incorrect.",
    "settings.pass_err_general": "An error occurred while updating the password: ",
    "settings.sub_cancel_confirm": "Are you sure you want to cancel your Premium subscription? You will lose access to Premium features.",
    "settings.sub_cancelled": "Your subscription has been cancelled.",
    "settings.restore_confirm": "Vehicle successfully restored to your garage!\\n\\nWould you like to go to your garage?",
    "settings.lbl_archived_title": "Archived Vehicles",
    "settings.lbl_restore": "Restore",
    "settings.msg_no_archived": "No archived vehicles found.",
    "settings.prem_title": "Subscription & Premium",
    "settings.prem_active_badge": "ACTIVE PLAN",
    "settings.prem_plan_name": "CarSync Pro Yearly",
    "settings.prem_all_active": "All features active",
    "settings.prem_renew": "Renewal: <1>Oct 12, 2024</1>",
    "settings.prem_payment": "Payment Method",
    "settings.prem_card_exp": "Mastercard - Expires 09/28",
    "settings.prem_change": "Change",
    "settings.prem_active_feats": "Active Features",
    "settings.feat_unlimited": "Unlimited Vehicles",
    "settings.feat_ai": "Advanced AI Diagnostic Analysis",
    "settings.feat_reports": "Detailed Fleet Reports",
    "settings.feat_no_ads": "Ad-free Experience",
    "settings.feat_support": "Priority Support",
    "settings.prem_cancel": "Cancel Subscription",
    "settings.prem_cancel_desc": "If you cancel, you can continue using the features until the end of your billing cycle (Oct 12, 2024).",
    "settings.free_title": "You are currently on the Free Plan",
    "settings.free_desc": "Upgrade to explore the full potential of CarSync Pro.",
    "settings.free_btn": "View Plans",
    "settings.free_missing": "What are you missing?",
    "settings.free_max2": "Max 2 Vehicles",
    "settings.free_in_free": "In Free Plan",
    "settings.free_unlimited": "Unlimited Vehicles",
    "settings.free_in_pro": "In Premium Plan",
    "settings.free_ai": "Detailed AI Analysis",
    "settings.free_ai_desc": "For DTCs and invoices",
    "settings.free_rep": "Advanced Reporting",
    "settings.free_rep_desc": "PDF exports and CSV downloads",
    "settings.free_ads": "Ad-free Usage",
    "settings.free_ads_desc": "Completely clean interface",
    "settings.legal_title": "About & Legal",
    "settings.legal_version": "Version 1.0.3 (Build 2024)",
    "settings.legal_desc": "Professional vehicle management, maintenance tracking, and AI-powered analysis application.",
    "settings.legal_texts": "Legal Documents",
    "settings.legal_privacy": "Privacy Policy",
    "settings.legal_terms": "Terms of Use",
    "settings.legal_data": "Data Usage and AI Services",
    "settings.legal_data_desc": "CarSync Pro uses <1>Google Gemini API</1> to provide features like invoice analysis and vehicle defect prediction.",
    "settings.rem_title": "Reminder Settings",
    "settings.rem_desc": "Set default maintenance intervals to be suggested automatically when adding logs.",
    "settings.rem_oil": "Oil Change",
    "settings.rem_every_km": "Every (km)",
    "settings.rem_every_mo": "Every (Months)",
    "settings.notif_title": "Notification Preferences",
    "settings.notif_events": "Event Notifications",
    "settings.notif_maint": "Maintenance Reminders",
    "settings.notif_fuel": "Fuel Consumption Alerts",
    "settings.notif_ins": "Insurance & Casco",
    "settings.notif_tax": "Vehicle Tax Payments",
    "settings.notif_dtc": "Critical Diagnostic Alerts",
    "settings.notif_news": "Campaigns and News",
    "settings.notif_channels": "Communication Channels",
    "settings.notif_push": "Push Notifications",
    "settings.sec_title": "Security Settings",
    "settings.sec_change": "Change Password",
    "settings.sec_cur": "Current Password",
    "settings.sec_new": "New Password",
    "settings.sec_confirm": "New Password (Confirm)",
    "settings.sec_update": "Update Password",
    "settings.sec_2fa": "Two-Factor Authentication (2FA)",
    "settings.sec_sms": "SMS Verification",
    "settings.sec_sms_desc": "A code will be sent to your phone upon login.",
    "settings.sec_2fa_active": "Two-factor authentication is enabled. A verification code will be sent to your registered phone number on your next login.",
    "settings.danger": "Danger Zone",
    "settings.wipe": "Wipe All Data",
    "settings.wipe_modal_title": "Wipe All Data?",
    "settings.wipe_modal_desc": "This action <1>cannot be undone</1>. All your vehicle records, settings, and history will be permanently deleted. The application will return to its initial state.",
    "settings.wipe_yes": "Yes, Wipe it"
};

Object.assign(tr, dictTR);
Object.assign(en, dictEN);

fs.writeFileSync(trPath, JSON.stringify(tr, null, 2), 'utf8');
fs.writeFileSync(enPath, JSON.stringify(en, null, 2), 'utf8');

console.log("Translation JSON files updated.");

// Now replace in component files
const replaceInFile = (filePath, rules) => {
    let content = fs.readFileSync(filePath, 'utf8');
    let original = content;

    if (!content.includes('useTranslation')) {
        content = content.replace(/import React(.*?) from 'react';/, "import React$1 from 'react';\nimport { useTranslation, Trans } from 'react-i18next';");
    }

    // Try to inject const { t } = useTranslation(); at appropriate places based on component definitions
    // Premium
    if (filePath.includes('Premium.tsx') && !content.includes('const { t } = useTranslation();')) {
        content = content.replace(/(export const Premium: React\.FC = \(\) => {\n)/, "$1  const { t } = useTranslation();\n");
    }
    // ServiceAppointment
    if (filePath.includes('ServiceAppointment.tsx') && !content.includes('const { t } = useTranslation();')) {
        content = content.replace(/(export const ServiceAppointment: React\.FC = \(\) => {\n)/, "$1  const { t } = useTranslation();\n");
        content = content.replace(/(const ApptModal: React\.FC<.*?> = \({.*?}\) => {\n)/, "$1  const { t } = useTranslation();\n");
        content = content.replace(/(const ApptCard: React\.FC<.*?> = \({.*?}\) => {\n)/, "$1  const { t } = useTranslation();\n");
        content = content.replace(/(const MiniCalendar: React\.FC<.*?> = \({.*?}\) => {\n)/, "$1  const { t } = useTranslation();\n");
    }

    // Apply rules
    rules.forEach(([search, replace]) => {
        content = content.split(search).join(replace);
    });

    if (content !== original) {
        fs.writeFileSync(filePath, content, 'utf8');
        console.log(`Updated ${path.basename(filePath)}`);
    }
};

// Premium rules
const premRules = [
    ['"Araç yönetiminde tüm sınırları kaldır, profesyonel özelliklere eriş."', "t('prem.desc')"],
    ['"CarSync Premium"', "t('prem.title')"],
    ['"Aylık"', "t('prem.monthly')"],
    ['"Yıllık"', "t('prem.yearly')"],
    ['>Aylık<', ">{t('prem.monthly')}<"],
    ['>Yıllık<', ">{t('prem.yearly')}<"],
    ['kullanıcı güveniyor', "{t('prem.trusted_by')}"],
    ['%{savingsPct} İndirim', "{t('prem.discount', { pct: savingsPct })}"],
    ['Yıllık planla ₺{MONTHLY_PRICE * 12 - YEARLY_PRICE} tasarruf edersin', "{t('prem.save_yearly', { amount: MONTHLY_PRICE * 12 - YEARLY_PRICE })}"],
    ["/yıl", "{t('prem.per_year')}"],
    ["/ay", "{t('prem.per_month')}"],
    ["Aylık ₺${monthlyEquiv}'ye geliyor · Tek seferlik ödeme", "{t('prem.yearly_desc', { amt: monthlyEquiv })}"],
    ["İstediğin zaman iptal et · Taahhüt yok", "t('prem.monthly_desc')"],
    ["<span>7 gün içinde memnun kalmazsan <span className=\\\"text-green-400 font-bold\\\">tam iade</span></span>", "<Trans i18nKey=\\\"prem.refund_notice\\\"><span>7 gün içinde memnun kalmazsan <span className=\\\"text-green-400 font-bold\\\">tam iade</span></span></Trans>"],
    ["Ücretsiz vs Premium", "{t('prem.compare_title')}"],
    ["Özellik</div>", "{t('prem.feature')}</div>"],
    ["Ücretsiz</div>", "{t('prem.free')}</div>"],
    ["Premium</div>", "{t('prem.premium')}</div>"],
    ["Araç sayısı", "t('prem.feat1')"], ["2 araç", "t('prem.feat1_free')"], ["Sınırsız", "t('prem.feat1_pro')"],
    ["Servis kaydı", "t('prem.feat2')"], ["50 kayıt", "t('prem.feat2_free')"],
    ["AI fatura analizi", "t('prem.feat3')"], ["3/ay", "t('prem.feat3_free')"],
    ["Araç karşılaştırma", "t('prem.feat4')"],
    ["CSV / PDF dışa aktarım", "t('prem.feat5')"],
    ["Gelişmiş analitik", "t('prem.feat6')"],
    ["Reklamsız deneyim", "t('prem.feat7')"],
    ["Öncelikli destek", "t('prem.feat8')"],
    ["Yakıt masraflarımı takip etmek çok kolaylaştı. Bir ayda ₺800 tasarruf ettim!", "{t('prem.testimonial')}"],
    ["Mehmet Y.", "{t('prem.user_name')}"],
    ["2 araç sahibi · 8 ay Premium kullanıcısı", "{t('prem.user_desc')}"],
    ["Kullanıcı", "{t('prem.trusted_by').split(' ')[0]}"], // Just a quick hack for badge text
    ["7 Gün\\nİade", "t('prem.badge_refund')"],
    ["SSL\\nGüvenli", "t('prem.badge_ssl')"],
    ["12.000+\\nKullanıcı", "t('prem.badge_users')"],
    ["<span>İşleniyor...</span>", "<span>{t('prem.processing')}</span>"],
    ["<span>Premium zaten aktif · Geri Dön</span>", "<span>{t('prem.already_active')}</span>"],
    ["<span>{billingCycle === 'yearly' ? `₺${YEARLY_PRICE}/yıl` : `₺${MONTHLY_PRICE}/ay`} ile Premium'a Geç</span>", "<span>{billingCycle === 'yearly' ? t('prem.upgrade_btn_year', {amt: YEARLY_PRICE}) : t('prem.upgrade_btn_month', {amt: MONTHLY_PRICE})}</span>"],
    ["Devam ederek Kullanım Koşulları ve Gizlilik Politikası'nı kabul etmiş olursunuz.", "{t('prem.terms')}"],
    ["<span>Aktif Plan</span>", "<span>{t('prem.active_plan')}</span>"]
];

replaceInFile(path.join(__dirname, 'pages', 'Premium.tsx'), premRules);

// ServiceAppointment rules
const apptRules = [
    ["'Yaklaşıyor'", "t('appt.upcoming')"],
    ["'Bugün!'", "t('appt.today_alert')"],
    ["'Gecikmiş'", "t('appt.overdue')"],
    ["'Tamamlandı'", "t('appt.completed')"],
    ["'Randevuyu Düzenle'", "t('appt.modal_edit')"],
    ["'Randevu Oluştur'", "t('appt.modal_new')"],
    ["Randevuyu Düzenle", "{t('appt.modal_edit')}"],
    ["Randevu Oluştur", "{t('appt.modal_new')}"],
    ["Araç</label>", "{t('appt.car')}</label>"],
    ["Servis Türü</label>", "{t('appt.service_type')}</label>"],
    ["Tahmini maliyet:", "{t('appt.est_cost')}"],
    ["Randevu Tarihi</label>", "{t('appt.date')}</label>"],
    ["Servis/Konum</label>", "{t('appt.location')}</label>"],
    ["Oto Servis İsmi", "t('appt.location_ph')"],
    ["Telefon</label>", "{t('appt.phone')}</label>"],
    ["Hatırlatma: ", "{t('appt.reminder')} "],
    ["{reminderDays} gün önce", "{t('appt.days_before', {days: reminderDays})}"],
    ["Not</label>", "{t('appt.notes')}</label>"],
    ["Özel talepler, araç anahtarı bırakma saati...", "t('appt.notes_ph')"],
    ["Güncelle", "{t('appt.btn_update')}"],
    ["// 'Randevu Oluştur' is mapped above via modal_new", ""],
    ["status === 'completed' ? 'Tamamlandı' :", "status === 'completed' ? t('appt.status_completed_label') :"],
    ["`${Math.abs(days)} gün gecikmiş`", "t('appt.days_overdue', {days: Math.abs(days)})"],
    ["status === 'today' ? 'Bugün!' :", "status === 'today' ? t('appt.today_alert') :"],
    ["days === 1 ? 'Yarın' :", "days === 1 ? t('appt.tomorrow') :"],
    ["`${days} gün kaldı`", "t('appt.days_left', {days})"],
    ["Hatırlatma aktif — {days} gün kaldı", "{t('appt.reminder_active', {days})}"],
    ["Randevular yükleniyor...", "{t('appt.loading')}"],
    ["Servis Randevuları", "{t('appt.title')}"],
    ["Planlama ve hatırlatma takvimi", "{t('appt.subtitle')}"],
    ["`Aktif (${stats.total})`", "t('appt.filter_active', {count: stats.total})"],
    ["{ key: 'completed', label: 'Tamamlandı' }", "{ key: 'completed', label: t('appt.filter_completed') }"],
    ["{ key: 'all', label: 'Tümü' }", "{ key: 'all', label: t('appt.filter_all') }"],
    ["{stats.overdue} gecikmiş randevu var — hemen planla!", "{t('appt.alert_overdue', {count: stats.overdue})}"],
    ["Bugün {stats.today} randevunuz var!", "{t('appt.alert_today', {count: stats.today})}"],
    ["{ label: 'Yaklaşan', value: stats.upcoming", "{ label: t('appt.stat_upcoming'), value: stats.upcoming"],
    ["{ label: 'Gecikmiş', value: stats.overdue", "{ label: t('appt.stat_overdue'), value: stats.overdue"],
    ["{ label: 'Bugün', value: stats.today", "{ label: t('appt.stat_today'), value: stats.today"],
    ["Randevu Yok", "{t('appt.no_appt')}"],
    ["Servis, muayene veya bakım randevusu oluştur. Tarih yaklaşınca otomatik hatırlatma alırsın.", "{t('appt.no_appt_desc')}"],
    ["İlk Randevuyu Oluştur", "{t('appt.btn_first')}"],
    [">Randevu<", ">{t('appt.legend_appt')}<"],
    [">Gecikmiş<", ">{t('appt.legend_overdue')}<"],
    [">Bugün<", ">{t('appt.legend_today')}<"],
    // Pass t properly inside ServiceAppointment helpers where possible, or just ignore for STATUS_CONFIG
    ["label: 'Yaklaşıyor'", "label: t('appt.upcoming')"],
    ["label: 'Bugün!'", "label: t('appt.today_alert')"],
    ["label: 'Gecikmiş'", "label: t('appt.overdue')"],
    ["label: 'Tamamlandı'", "label: t('appt.completed')"],
];

const replaceInServiceAppointment = (filePath, apptRules) => {
    let content = fs.readFileSync(filePath, 'utf8');

    if (!content.includes('useTranslation')) {
        content = content.replace(/import { useNavigate } from 'react-router-dom';/, "import { useNavigate } from 'react-router-dom';\nimport { useTranslation, Trans } from 'react-i18next';");
    }

    // Convert STATUS_CONFIG to function
    content = content.replace(
        /const STATUS_CONFIG:(.*?)=(.*?){(.*?)}/s,
        "const STATUS_CONFIG = (t: any): Record<ApptStatus, { label: string; color: string; bg: string; border: string; dotColor: string }> => ({\n  upcoming: { label: t('appt.upcoming'), color: 'text-blue-400', bg: 'bg-blue-500/10', border: 'border-blue-500/20', dotColor: 'bg-blue-500' },\n  today: { label: t('appt.today_alert'), color: 'text-emerald-400', bg: 'bg-emerald-500/10', border: 'border-emerald-500/30', dotColor: 'bg-emerald-500 animate-pulse' },\n  overdue: { label: t('appt.overdue'), color: 'text-red-400', bg: 'bg-red-500/10', border: 'border-red-500/30', dotColor: 'bg-red-500' },\n  completed: { label: t('appt.completed'), color: 'text-slate-400', bg: 'bg-slate-500/10', border: 'border-slate-700/30', dotColor: 'bg-slate-500' },\n});"
    );

    content = content.replace(/const scfg = STATUS_CONFIG\[status\];/g, "const scfg = STATUS_CONFIG(t)[status];");
    content = content.replace(/import React, {(.+?)} from 'react';/, "import React, { $1 } from 'react';\nimport { useTranslation, Trans } from 'react-i18next';");

    // Delete duplicate import if exists
    content = content.replace(/import \{ useTranslation, Trans \} from 'react-i18next';\nimport \{ useTranslation, Trans \} from 'react-i18next';/g, "import { useTranslation, Trans } from 'react-i18next';");

    if (!content.includes('const { t } = useTranslation()')) {
        content = content.replace(/export const ServiceAppointment: React.FC = \(\) => {/g, "export const ServiceAppointment: React.FC = () => {\n  const { t } = useTranslation();");
        content = content.replace(/const ApptModal: React.FC<.*?> = \({.*?}\) => {/s, (match) => match + "\n  const { t } = useTranslation();");
        content = content.replace(/const ApptCard: React.FC<.*?> = \({.*?}\) => {/s, (match) => match + "\n  const { t } = useTranslation();");
        content = content.replace(/const MiniCalendar: React.FC<{ appointments: Appointment\[\] }> = \({ appointments }\) => {/g, "const MiniCalendar: React.FC<{ appointments: Appointment[] }> = ({ appointments }) => {\n  const { t } = useTranslation();");
    }

    apptRules.forEach(([search, replace]) => {
        content = content.split(search).join(replace);
    });

    fs.writeFileSync(filePath, content, 'utf8');
};

replaceInServiceAppointment(path.join(__dirname, 'pages', 'ServiceAppointment.tsx'), apptRules);


// Settings Rules
const settingsRules = [
    ["Profil başarıyla güncellendi!", "t('settings.msg_saved')"],
    ["Profil güncellenirken bir hata oluştu.", "t('settings.msg_err')"],
    ["Hatırlatıcı tercihleri kaydedildi.", "t('settings.reminders_saved')"],
    ["Ayarlar kaydedildi. \\\"Yaklaşan Servis\\\" ve \\\"Yakıt Uyarıları\\\" aktif!", "t('settings.notif_saved_full')"],
    ["Bildirim tercihleri başarıyla kaydedildi.", "t('settings.notif_saved')"],
    ["Yeni şifreler eşleşmiyor!", "t('settings.pass_mismatch')"],
    ["Şifre en az 6 karakter olmalıdır.", "t('settings.pass_short')"],
    ["Şifreniz başarıyla güncellendi.", "t('settings.pass_success')"],
    ["Mevcut şifre hatalı.", "t('settings.pass_err_wrong')"],
    ["'Şifre güncellenirken bir hata oluştu: ' + error.message", "t('settings.pass_err_general') + error.message"],
    ["Premium üyeliğinizi iptal etmek istediğinize emin misiniz?", "t('settings.sub_cancel_confirm')"],
    ["Üyeliğiniz iptal edildi.", "t('settings.sub_cancelled')"],
    ["Araç başarıyla garajınıza geri yüklendi!\\n\\nGarajınıza gitmek ister misiniz?", "t('settings.restore_confirm')"],

    // UI texts
    [">Ayarlar<", ">{t('settings.title')}<"],
    [">Kaydet<", ">{t('settings.save')}<"],
    ["title=\"Galeriden Seç\"", "title={t('settings.upload_gallery')}"],
    ["title=\"Fotoğraf Çek\"", "title={t('settings.take_photo')}"],
    [">PRO<", ">{t('settings.badge_pro')}<"],
    [">Profili Düzenle<", ">{t('settings.edit_profile')}<"],
    [">İSİM<", ">{t('settings.lbl_name')}<"],
    [">SOYİSİM<", ">{t('settings.lbl_surname')}<"],
    [">E-POSTA<", ">{t('settings.lbl_email')}<"],
    [">TELEFON<", ">{t('settings.lbl_phone')}<"],
    [">BÖLÜM / DEPARTMAN<", ">{t('settings.lbl_dept')}<"],
    ["placeholder=\"İsim\"", "placeholder={t('settings.ph_name')}"],
    ["placeholder=\"Soyisim\"", "placeholder={t('settings.ph_surname')}"],
    ["placeholder=\"E-posta Adresi\"", "placeholder={t('settings.ph_email')}"],
    ["placeholder=\"Telefon Numarası\"", "placeholder={t('settings.ph_phone')}"],
    ["placeholder=\"Örn: Muhasebe, İK, Satış...\"", "placeholder={t('settings.ph_dept')}"],
    [">İptal<", ">{t('settings.cancel')}<"],
    [">PRO ÖZELLİKLER<", ">{t('settings.promo_features')}<"],
    [">Premium'a Yükselt<", ">{t('settings.promo_title')}<"],
    ["Sınırsız araç ekle, yapay zeka analizlerini kullan ve detaylı raporlara eriş.", "{t('settings.promo_desc')}"],
    [">Hemen Başla<", ">{t('settings.promo_btn')}<"],
    [">Genel<", ">{t('settings.sec_general')}<"],
    [">Bildirimler<", ">{t('settings.notifications')}<"],
    [">Yazı Boyutu<", ">{t('settings.font_size')}<"],
    [">Küçük<", ">{t('settings.font_small')}<"],
    [">Orta<", ">{t('settings.font_medium')}<"],
    [">Büyük<", ">{t('settings.font_large')}<"],
    [">Arka Plan Teması<", ">{t('settings.bg_theme')}<"],
    [">Varsayılan<", ">{t('settings.bg_default')}<"],
    [">Mavi Ton<", ">{t('settings.bg_blue')}<"],
    [">Mesh<", ">{t('settings.bg_mesh')}<"],
    [">Hatırlatıcı Varsayılanları<", ">{t('settings.reminders')}<"],
    [">Karanlık Mod<", ">{t('settings.dark_mode')}<"],
    [">Abonelik<", ">{t('settings.sec_sub')}<"],
    [">Aktif: Yıllık Plan<", ">{t('settings.sub_active')}<"],
    [">Ücretsiz Plan<", ">{t('settings.sub_free')}<"],
    [">Veri Yönetimi<", ">{t('settings.sec_data')}<"],
    ["Araç Listesi (CSV)", "{t('settings.csv_vehicles')}"],
    ["Servis Geçmişi (CSV)", "{t('settings.csv_history')}"],
    ["Garaj Raporu (PDF)", "{t('settings.pdf_report')}"],
    [">Abonelik & Premium<", ">{t('settings.prem_title')}<"],
    [">Arşivlenmiş Araçlar<", ">{t('settings.archived')}<"],
    [">Güvenlik<", ">{t('settings.security')}<"],
    [">Hakkında & Yasal<", ">{t('settings.legal')}<"],
    [">Çıkış Yap<", ">{t('settings.logout')}<"],
    ["'Çıkış yapmak istediğinize emin misiniz?'", "t('settings.logout_confirm')"],

    [">Geri Yükle<", ">{t('settings.lbl_restore')}<"],
    [">Arşivlenmiş araç bulunmuyor.<", ">{t('settings.msg_no_archived')}<"],
    [">AKTİF PLAN<", ">{t('settings.prem_active_badge')}<"],
    [">CarSync Pro Yıllık<", ">{t('settings.prem_plan_name')}<"],
    [">Tüm özellikler aktif<", ">{t('settings.prem_all_active')}<"],
    ["Yenilenme: <strong>12 Ekim 2024</strong>", "<Trans i18nKey=\"settings.prem_renew\">Yenilenme: <strong>12 Ekim 2024</strong></Trans>"],
    [">Ödeme Yöntemi<", ">{t('settings.prem_payment')}<"],
    [">Mastercard - Sona erme 09/28<", ">{t('settings.prem_card_exp')}<"],
    [">Değiştir<", ">{t('settings.prem_change')}<"],
    [">Aktif Özellikler<", ">{t('settings.prem_active_feats')}<"],
    ["Sınırsız Araç Ekleme", "t('settings.feat_unlimited')"],
    ["Gelişmiş AI Arıza Analizi", "t('settings.feat_ai')"],
    ["Detaylı Filo Raporları", "t('settings.feat_reports')"],
    ["Reklamsız Deneyim", "t('settings.feat_no_ads')"],
    ["Öncelikli Destek", "t('settings.feat_support')"],
    [">Üyeliği İptal Et<", ">{t('settings.prem_cancel')}<"],
    ["İptal ederseniz, fatura döneminizin sonuna kadar (12 Ekim 2024) özelliklerden yararlanmaya devam edebilirsiniz.", "{t('settings.prem_cancel_desc')}"],
    [">Şu an Ücretsiz Plandasınız<", ">{t('settings.free_title')}<"],
    ["CarSync Pro'nun tüm potansiyelini keşfetmek için yükseltin.", "{t('settings.free_desc')}"],
    [">Planları İncele<", ">{t('settings.free_btn')}<"],
    [">Neler Kaçırıyorsunuz?<", ">{t('settings.free_missing')}<"],
    [">Maks 2 Araç<", ">{t('settings.free_max2')}<"],
    [">Ücretsiz Planda<", ">{t('settings.free_in_free')}<"],
    [">Sınırsız Araç<", ">{t('settings.free_unlimited')}<"],
    [">Premium Planda<", ">{t('settings.free_in_pro')}<"],
    // We need to map the object array for the features in Free plan:
    // `{ title: "Detaylı Yapay Zeka Analizi", sub: "Arıza kodları ve faturalar için" }`
    ["\"Detaylı Yapay Zeka Analizi\"", "t('settings.free_ai')"], ["\"Arıza kodları ve faturalar için\"", "t('settings.free_ai_desc')"],
    ["\"Gelişmiş Raporlama\"", "t('settings.free_rep')"], ["\"PDF dökümü ve CSV çıktısı\"", "t('settings.free_rep_desc')"],
    ["\"Reklamsız Kullanım\"", "t('settings.free_ads')"], ["\"Tamamen temiz arayüz\"", "t('settings.free_ads_desc')"],
    [">Sürüm 1.0.3", ">{t('settings.legal_version')}"],
    ["Profesyonel araç yönetimi, bakım takibi ve yapay zeka destekli analiz uygulaması.", "{t('settings.legal_desc')}"],
    [">Yasal Metinler<", ">{t('settings.legal_texts')}<"],
    [">Gizlilik Politikası<", ">{t('settings.legal_privacy')}<"],
    [">Kullanım Koşulları<", ">{t('settings.legal_terms')}<"],
    [">Veri Kullanımı ve AI Servisleri<", ">{t('settings.legal_data')}<"],
    ["CarSync Pro, fatura analizi ve araç arıza tahmini gibi özellikler sunmak için <strong>Google Gemini API</strong> kullanır.", "<Trans i18nKey=\"settings.legal_data_desc\">CarSync Pro, fatura analizi ve araç arıza tahmini gibi özellikler sunmak için <strong>Google Gemini API</strong> kullanır.</Trans>"],
    [">Hatırlatıcı Ayarları<", ">{t('settings.rem_title')}<"],
    ["Kayıt eklerken otomatik olarak önerilecek varsayılan bakım aralıklarını belirleyin.", "{t('settings.rem_desc')}"],
    [">Yağ Değişimi<", ">{t('settings.rem_oil')}<"],
    [">Her (km)<", ">{t('settings.rem_every_km')}<"],
    [">Her (Ay)<", ">{t('settings.rem_every_mo')}<"],
    [">Bildirim Tercihleri<", ">{t('settings.notif_title')}<"],
    [">Olay Bildirimleri<", ">{t('settings.notif_events')}<"],
    [">Bakım Hatırlatmaları<", ">{t('settings.notif_maint')}<"],
    [">Yakıt Tüketim Uyarıları<", ">{t('settings.notif_fuel')}<"],
    [">Sigorta & Kasko<", ">{t('settings.notif_ins')}<"],
    [">Vergi (MTV) Ödemeleri<", ">{t('settings.notif_tax')}<"],
    [">Kritik Arıza Bildirimleri<", ">{t('settings.notif_dtc')}<"],
    [">Kampanya ve Haberler<", ">{t('settings.notif_news')}<"],
    [">İletişim Kanalları<", ">{t('settings.notif_channels')}<"],
    [">Anlık Bildirimler<", ">{t('settings.notif_push')}<"],
    [">Güvenlik Ayarları<", ">{t('settings.sec_title')}<"],
    [">Şifre Değiştir<", ">{t('settings.sec_change')}<"],
    [">Mevcut Şifre<", ">{t('settings.sec_cur')}<"],
    [">Yeni Şifre<", ">{t('settings.sec_new')}<"],
    [">Yeni Şifre (Tekrar)<", ">{t('settings.sec_confirm')}<"],
    [">Şifreyi Güncelle<", ">{t('settings.sec_update')}<"],
    [">İki Faktörlü Doğrulama (2FA)<", ">{t('settings.sec_2fa')}<"],
    [">SMS Doğrulama<", ">{t('settings.sec_sms')}<"],
    [">Giriş yaparken telefonunuza kod gönderilir.<", ">{t('settings.sec_sms_desc')}<"],
    ["İki faktörlü doğrulama etkinleştirildi. Bir sonraki girişinizde kayıtlı telefon numaranıza doğrulama kodu gönderilecektir.", "{t('settings.sec_2fa_active')}"],
    [">Tehlikeli Bölge<", ">{t('settings.danger')}<"],
    [">Tüm Verileri Sil<", ">{t('settings.wipe')}<"],
    [">Tüm Verileri Sil?<", ">{t('settings.wipe_modal_title')}<"],
    ["Bu işlem <strong className=\"text-white\">geri alınamaz</strong>. Tüm araç kayıtlarınız, ayarlarınız ve geçmişiniz kalıcı olarak silinecektir. Uygulama başlangıç durumuna dönecektir.", "<Trans i18nKey=\"settings.wipe_modal_desc\">Bu işlem <strong className=\"text-white\">geri alınamaz</strong>. Tüm araç kayıtlarınız, ayarlarınız ve geçmişiniz kalıcı olarak silinecektir. Uygulama başlangıç durumuna dönecektir.</Trans>"],
    [">Evet, Sil<", ">{t('settings.wipe_yes')}<"],
];

let settingsContent = fs.readFileSync(path.join(__dirname, 'pages', 'Settings.tsx'), 'utf8');
if (!settingsContent.includes("import { Trans } from 'react-i18next'")) {
    settingsContent = settingsContent.replace(/import \{ useTranslation \} from 'react-i18next';/, "import { useTranslation, Trans } from 'react-i18next';");
}
settingsRules.forEach(([s, r]) => {
    settingsContent = settingsContent.split(s).join(r);
});
fs.writeFileSync(path.join(__dirname, 'pages', 'Settings.tsx'), settingsContent, 'utf8');

console.log("All components processed successfully.");
