const fs = require('fs');

const trPath = 'src/locales/tr/translation.json';
const enPath = 'src/locales/en/translation.json';

const trData = JSON.parse(fs.readFileSync(trPath, 'utf8'));
const enData = JSON.parse(fs.readFileSync(enPath, 'utf8'));

trData.damageDetect = {
    "title": "Hasar Tespiti", "subtitle": "AI destekli görsel hasar analizi",
    "upload_title": "Araç Fotoğrafı Yükle", "upload_desc": "Sürükle bırak veya tıkla",
    "gallery": "Galeri", "camera": "Kamera", "reqs": "JPG, PNG, WEBP · Max 10MB",
    "diff_photo": "Farklı fotoğraf seç", "btn_detect": "Hasarı Tespit Et",
    "analyzing_ai": "AI analiz ediyor...", "analyzing_img": "Görüntü analiz ediliyor...",
    "analyzing_scan": "AI hasar noktalarını tarıyor",
    "step_1": "Hasar noktaları tespit ediliyor", "step_2": "Ciddiyet seviyeleri değerlendiriliyor", "step_3": "Maliyet tahmini hesaplanıyor",
    "err_title": "Analiz Başarısız", "err_retry": "Tekrar Dene",
    "show_visual": "Görsel Raporu Göster", "show_json": "JSON Olarak Göster",
    "safety_risk": "Güvenlik Riski Var", "total_cost": "Toplam Tahmini Onarım",
    "priority_action": "Öncelikli İşlem", "detected_damages": "Tespit Edilen Hasarlar",
    "show_more": "{{c}} hasar daha göster", "show_less": "Daha Az Göster",
    "ai_recs": "AI Önerileri", "new_analysis": "Yeni Fotoğraf Analiz Et",
    "disclaimer": "Hasar tespiti ve maliyet tahminleri AI görsel analizi ile oluşturulmuştur. Kesin sonuçlar için yetkili bir servis veya oto eksper danışmanını ziyaret ediniz.",

    "sev_crit": "Kritik", "sev_maj": "Büyük", "sev_min": "Küçük", "sev_none": "Hasar Yok",
    "rep_paint": "🎨 Boya İşlemi", "rep_body": "🔨 Kaporta", "rep_glass": "🪟 Cam",
    "rep_mech": "⚙️ Mekanik", "rep_cosm": "✨ Kozmetik", "rep_none": "✅ İşlem Gerekmez",
    "diy": "🔧 Kendin Yapabilirsin", "est_cost": "Tahmini Maliyet", "hours": "{{h}} saat"
};

enData.damageDetect = {
    "title": "Damage Detection", "subtitle": "AI-powered visual damage analysis",
    "upload_title": "Upload Vehicle Photo", "upload_desc": "Drag & drop or click",
    "gallery": "Gallery", "camera": "Camera", "reqs": "JPG, PNG, WEBP · Max 10MB",
    "diff_photo": "Choose different photo", "btn_detect": "Detect Damage",
    "analyzing_ai": "AI analyzing...", "analyzing_img": "Image is being analyzed...",
    "analyzing_scan": "AI is scanning for damage points",
    "step_1": "Detecting damage points", "step_2": "Evaluating severity levels", "step_3": "Calculating estimated cost",
    "err_title": "Analysis Failed", "err_retry": "Try Again",
    "show_visual": "Show Visual Report", "show_json": "Show as JSON",
    "safety_risk": "Safety Risk Detected", "total_cost": "Total Estimated Repair",
    "priority_action": "Priority Action", "detected_damages": "Detected Damages",
    "show_more": "Show {{c}} more damages", "show_less": "Show Less",
    "ai_recs": "AI Recommendations", "new_analysis": "Analyze New Photo",
    "disclaimer": "Damage detection and cost estimates are generated by AI visual analysis. For precise results, please visit an authorized service or auto appraiser.",

    "sev_crit": "Critical", "sev_maj": "Major", "sev_min": "Minor", "sev_none": "No Damage",
    "rep_paint": "🎨 Paintwork", "rep_body": "🔨 Bodywork", "rep_glass": "🪟 Glass",
    "rep_mech": "⚙️ Mechanical", "rep_cosm": "✨ Cosmetic", "rep_none": "✅ No Action Needed",
    "diy": "🔧 DIY Possible", "est_cost": "Estimated Cost", "hours": "{{h}} hours"
};

trData.fuelReminder = {
    "title": "Yakıt Takibi", "subtitle": "Menzil tahmini ve doldurma hatırlatıcısı",
    "settings": "Yakıt Ayarları", "tank_cap": "Depo Kapasitesi (Litre)",
    "avg_cons": "Ortalama Tüketim (L/100km)", "auto_calc": "Otomatik hesaplanan",
    "active": "aktif", "ph_auto": "Boş = otomatik ({{a}})", "warning_thr": "Uyarı Eşiği:", "save": "Kaydet",
    "calculating": "Yakıt verileri hesaplanıyor...",
    "crit_title": "Yakıt Kritik Seviyede!", "warn_title": "Yakıt Doldurmayı Planla",
    "crit_desc": "Tahmini ~{{r}} km menzil kaldı. Hemen doldur.",
    "warn_desc": "%{{p}} doluluk. Yakında doldurman öneriliyor.",
    "station": "İstasyon", "enough_fuel": "Yeterli Yakıt",

    "d_today": "Bugün", "d_yest": "Dün", "d_days": "{{d}} gün önce", "no_rec": "Kayıt yok",
    "last_fill": "Son Dolum", "km_since": "Son Dolumdan Km", "avg_c": "Ort. Tüketim",
    "manual": "(manuel)", "fill_rec": "Doldurma Önerisi", "after_km": "~{{k}} km sonra", "fill_now": "Şimdi doldur!",

    "tr_imp": "İyileşiyor", "tr_wor": "Kötüleşiyor", "tr_stb": "Sabit", "tr_no": "Yeterli veri yok",
    "trend": "Tüketim Trendi", "tt_val": "Tüketim", "ref_line": "--- {{v}} L/100km referans çizgisi",

    "tips_title": "Yakıt Tasarrufu İpuçları",
    "tip_1": "Düzenli lastik basıncı kontrolü %3 yakıt tasarrufu sağlar.",
    "tip_2": "Ani fren ve hızlanmadan kaçının — sabit hız daha az yakar.",
    "tip_3": "Motor ısınınca yolculuk başlatmak soğuk çalışmadan daha verimli.",

    "add_rec": "Yakıt Kaydı Ekle", "find_station": "İstasyon Bul",
    "disclaimer": "Menzil tahmini geçmiş yakıt kayıtlarından hesaplanır. Sürüş koşulları, trafik ve klima kullanımı gerçek menzili etkileyebilir. Kesin sonuç için yakıt göstergenize bakın.",

    "no_data_title": "Yakıt Verisi Yok", "no_data_desc": "Tahmin yapabilmek için yakıt alımı kaydı ekle. Litre bilgisini girerek tüketim analizi başlar.",
    "first_rec": "İlk Yakıt Kaydını Ekle",
    "est_fill": "Tahmini Doluluk", "empty": "Boş", "full": "Dolu"
};

enData.fuelReminder = {
    "title": "Fuel Tracker", "subtitle": "Range estimate and refill reminder",
    "settings": "Fuel Settings", "tank_cap": "Tank Capacity (Liters)",
    "avg_cons": "Avg Consumption (L/100km)", "auto_calc": "Auto-calculated",
    "active": "active", "ph_auto": "Empty = auto ({{a}})", "warning_thr": "Warning Threshold:", "save": "Save",
    "calculating": "Calculating fuel data...",
    "crit_title": "Fuel is Critical!", "warn_title": "Plan Refill Soon",
    "crit_desc": "Estimated ~{{r}} km range left. Refill immediately.",
    "warn_desc": "{{p}}% fuel left. Refill is recommended soon.",
    "station": "Station", "enough_fuel": "Sufficient Fuel",

    "d_today": "Today", "d_yest": "Yesterday", "d_days": "{{d}} days ago", "no_rec": "No record",
    "last_fill": "Last Refill", "km_since": "Km Since Last Fill", "avg_c": "Avg Consumption",
    "manual": "(manual)", "fill_rec": "Refill Suggestion", "after_km": "~{{k}} km left", "fill_now": "Refill now!",

    "tr_imp": "Improving", "tr_wor": "Worsening", "tr_stb": "Stable", "tr_no": "Not enough data",
    "trend": "Consumption Trend", "tt_val": "Consumption", "ref_line": "--- {{v}} L/100km reference line",

    "tips_title": "Fuel Saving Tips",
    "tip_1": "Regular tire pressure checks save 3% fuel.",
    "tip_2": "Avoid sudden braking and acceleration — steady speed uses less fuel.",
    "tip_3": "Starting trip when engine is warm is more efficient than cold start.",

    "add_rec": "Add Fuel Record", "find_station": "Find Station",
    "disclaimer": "Range estimation is calculated from past fuel records. Driving conditions, traffic, and AC usage can affect actual range. Check your fuel gauge for definitive results.",

    "no_data_title": "No Fuel Data", "no_data_desc": "Add a fuel supply record to make an estimate. Entering liter info starts consumption analysis.",
    "first_rec": "Add First Fuel Record",
    "est_fill": "Estimated Fill", "empty": "Empty", "full": "Full"
};


fs.writeFileSync(trPath, JSON.stringify(trData, null, 4));
fs.writeFileSync(enPath, JSON.stringify(enData, null, 4));

// --- DAMAGE DETECTION ---
let dd = fs.readFileSync('pages/DamageDetection.tsx', 'utf8');

if (!dd.includes('useTranslation')) {
    dd = dd.replace(
        "import { useNavigate } from 'react-router-dom';",
        "import { useNavigate } from 'react-router-dom';\nimport { useTranslation } from 'react-i18next';"
    );
}

dd = dd.replace("export const DamageDetection: React.FC = () => {\n  const navigate = useNavigate();", "export const DamageDetection: React.FC = () => {\n  const navigate = useNavigate();\n  const { t } = useTranslation();");
dd = dd.replace(/const DamageCard: React\.FC<\{ damage: DamageItem; index: number \}> = \(\{ damage, index \}\) => \{/g, "const DamageCard: React.FC<{ damage: DamageItem; index: number; t: any }> = ({ damage, index, t }) => {");
dd = dd.replace(/<DamageCard key=\{i\} damage=\{d\} index=\{i\} \/>/g, "<DamageCard key={i} damage={d} index={i} t={t} />");

dd = dd.replace("label: 'Kritik'", "label: t('damageDetect.sev_crit')");
dd = dd.replace("label: 'Büyük'", "label: t('damageDetect.sev_maj')");
dd = dd.replace("label: 'Küçük'", "label: t('damageDetect.sev_min')");
dd = dd.replace("label: 'Hasar Yok'", "label: t('damageDetect.sev_none')");

dd = dd.replace("paintwork:  '🎨 Boya İşlemi',", "paintwork: t('damageDetect.rep_paint'),");
dd = dd.replace("bodywork:   '🔨 Kaporta',", "bodywork: t('damageDetect.rep_body'),");
dd = dd.replace("glass:      '🪟 Cam',", "glass: t('damageDetect.rep_glass'),");
dd = dd.replace("mechanical: '⚙️ Mekanik',", "mechanical: t('damageDetect.rep_mech'),");
dd = dd.replace("cosmetic:   '✨ Kozmetik',", "cosmetic: t('damageDetect.rep_cosm'),");
dd = dd.replace("none:       '✅ İşlem Gerekmez',", "none: t('damageDetect.rep_none'),");

// DamageCard updates
dd = dd.replace("⏱ {damage.repairTimeHours} saat", "⏱ {t('damageDetect.hours', { h: damage.repairTimeHours })}");
dd = dd.replace("🔧 Kendin Yapabilirsin", "{t('damageDetect.diy')}");
dd = dd.replace(">Tahmini Maliyet</p>", ">{t('damageDetect.est_cost')}</p>");
// Update SEVERITY_CONFIG inside DamageCard
dd = dd.replace("const cfg = SEVERITY_CONFIG[damage.severity];", `  const cfgRaw = SEVERITY_CONFIG[damage.severity];
  const cfg = {
    ...cfgRaw,
    label: damage.severity === 'critical' ? t('damageDetect.sev_crit') : damage.severity === 'major' ? t('damageDetect.sev_maj') : damage.severity === 'minor' ? t('damageDetect.sev_min') : t('damageDetect.sev_none')
  };`);
dd = dd.replace("const REPAIR_TYPE_LABELS: Record<string, string> = {", "");


// Main updates
dd = dd.replace("setError('Analiz başarısız oldu. Lütfen daha net bir fotoğraf deneyin veya tekrar deneyiniz.');", "setError(t('damageDetect.err_title'));");

dd = dd.replace(">Hasar Tespiti</h1>", ">{t('damageDetect.title')}</h1>");
dd = dd.replace(">AI destekli görsel hasar analizi</p>", ">{t('damageDetect.subtitle')}</p>");
dd = dd.replace(">Araç Fotoğrafı Yükle</p>", ">{t('damageDetect.upload_title')}</p>");
dd = dd.replace(">Sürükle bırak veya tıkla</p>", ">{t('damageDetect.upload_desc')}</p>");
dd = dd.replace("\n                Galeri\n", "\n                {t('damageDetect.gallery')}\n");
dd = dd.replace("\n                Kamera\n", "\n                {t('damageDetect.camera')}\n");
dd = dd.replace(">JPG, PNG, WEBP · Max 10MB</p>", ">{t('damageDetect.reqs')}</p>");
dd = dd.replace("\n                  Farklı fotoğraf seç\n", "\n                  {t('damageDetect.diff_photo')}\n");
dd = dd.replace("\n                Hasarı Tespit Et\n", "\n                {t('damageDetect.btn_detect')}\n");
dd = dd.replace("\n                AI analiz ediyor...\n", "\n                {t('damageDetect.analyzing_ai')}\n");
dd = dd.replace(">Görüntü analiz ediliyor...</p>", ">{t('damageDetect.analyzing_img')}</p>");
dd = dd.replace(">AI hasar noktalarını tarıyor</p>", ">{t('damageDetect.analyzing_scan')}</p>");

// Steps map
const oldSteps = `['Hasar noktaları tespit ediliyor', 'Ciddiyet seviyeleri değerlendiriliyor', 'Maliyet tahmini hesaplanıyor']`;
const newSteps = `[t('damageDetect.step_1'), t('damageDetect.step_2'), t('damageDetect.step_3')]`;
dd = dd.replace(oldSteps, newSteps);

dd = dd.replace(">Analiz Başarısız</p>", ">{t('damageDetect.err_title')}</p>");
dd = dd.replace("Tekrar Dene\n", "{t('damageDetect.err_retry')}\n");
dd = dd.replace("{showJson ? 'Görsel Raporu Göster' : 'JSON Olarak Göster'}", "{showJson ? t('damageDetect.show_visual') : t('damageDetect.show_json')}");
dd = dd.replace(">Güvenlik Riski Var</p>", ">{t('damageDetect.safety_risk')}</p>");
dd = dd.replace(">Toplam Tahmini Onarım</p>", ">{t('damageDetect.total_cost')}</p>");
dd = dd.replace(">Öncelikli İşlem</p>", ">{t('damageDetect.priority_action')}</p>");
dd = dd.replace("\n                  Tespit Edilen Hasarlar\n", "\n                  {t('damageDetect.detected_damages')}\n");
dd = dd.replace("{showAllDamages ? 'Daha Az Göster' : `${report.damages.length - 3} hasar daha göster`}", "{showAllDamages ? t('damageDetect.show_less') : t('damageDetect.show_more', { c: report.damages.length - 3 })}");
dd = dd.replace(">AI Önerileri</p>", ">{t('damageDetect.ai_recs')}</p>");
dd = dd.replace("\n              Yeni Fotoğraf Analiz Et\n", "\n              {t('damageDetect.new_analysis')}\n");
dd = dd.replace("Hasar tespiti ve maliyet tahminleri AI görsel analizi ile oluşturulmuştur. \n                Kesin sonuçlar için yetkili bir servis veya oto eksper danışmanını ziyaret ediniz.", "{t('damageDetect.disclaimer')}");
dd = dd.replace("Hasar tespiti ve maliyet tahminleri AI görsel analizi ile oluşturulmuştur.\n                Kesin sonuçlar için yetkili bir servis veya oto eksper danışmanını ziyaret ediniz.", "{t('damageDetect.disclaimer')}");

fs.writeFileSync('pages/DamageDetection.tsx', dd);

// --- FUEL REMINDER ---
let fr = fs.readFileSync('pages/FuelReminder.tsx', 'utf8');

if (!fr.includes('useTranslation')) {
    fr = fr.replace(
        "import { useNavigate } from 'react-router-dom';",
        "import { useNavigate } from 'react-router-dom';\nimport { useTranslation } from 'react-i18next';"
    );
}

// Pass t down
fr = fr.replace("const ProfilePanel: React.FC<{\n  profile: FuelProfile;", "const ProfilePanel: React.FC<{\n  profile: FuelProfile;\n  t: any;\n");
fr = fr.replace("onClose: () => void;\n}> = ({ profile, autoConsumption, onSave, onClose }) => {", "onClose: () => void;\n}> = ({ profile, autoConsumption, onSave, onClose, t }) => {");

fr = fr.replace(">Yakıt Ayarları</h3>", ">{t('fuelReminder.settings')}</h3>");
fr = fr.replace("\n            Depo Kapasitesi (Litre)\n", "\n            {t('fuelReminder.tank_cap')}\n");
fr = fr.replace("\n            Ortalama Tüketim (L/100km)\n", "\n            {t('fuelReminder.avg_cons')}\n");
fr = fr.replace("Otomatik hesaplanan:", "{t('fuelReminder.auto_calc')}:");
fr = fr.replace("(!override && ' (aktif)')", "(!override && ' (' + t('fuelReminder.active') + ')')");
fr = fr.replace("placeholder={autoConsumption ? `Boş = otomatik (${autoConsumption})` : 'örn: 8.5'}", "placeholder={autoConsumption ? t('fuelReminder.ph_auto', { a: autoConsumption }) : 'örn: 8.5'}");
fr = fr.replace("Uyarı Eşiği:", "{t('fuelReminder.warning_thr')}");
fr = fr.replace("\n          Kaydet\n", "\n          {t('fuelReminder.save')}\n");

fr = fr.replace("const TankGauge: React.FC<{ pct: number; range: number; urgency: FuelEstimate['urgency'] }> = ({ pct, range, urgency }) => {", "const TankGauge: React.FC<{ pct: number; range: number; urgency: FuelEstimate['urgency']; t: any }> = ({ pct, range, urgency, t }) => {");
fr = fr.replace(">Tahmini Doluluk</p>", ">{t('fuelReminder.est_fill')}</p>");
fr = fr.replace(">Boş</span>", ">{t('fuelReminder.empty')}</span>");
fr = fr.replace(">Dolu</span>", ">{t('fuelReminder.full')}</span>");

fr = fr.replace("export const FuelReminder: React.FC = () => {\n  const navigate = useNavigate();", "export const FuelReminder: React.FC = () => {\n  const navigate = useNavigate();\n  const { t } = useTranslation();");

fr = fr.replace(">Yakıt verileri hesaplanıyor...</p>", ">{t('fuelReminder.calculating')}</p>");

fr = fr.replace(">Yakıt Takibi</h1>", ">{t('fuelReminder.title')}</h1>");
fr = fr.replace(">Menzil tahmini ve doldurma hatırlatıcısı</p>", ">{t('fuelReminder.subtitle')}</p>");

fr = fr.replace("{estimate.urgency === 'critical' ? 'Yakıt Kritik Seviyede!' : 'Yakıt Doldurmayı Planla'}", "{estimate.urgency === 'critical' ? t('fuelReminder.crit_title') : t('fuelReminder.warn_title')}");
fr = fr.replace("? `Tahmini ~${estimate.estimatedRange} km menzil kaldı. Hemen doldur.`\n                    : `%${estimate.estimatedRangePct} doluluk. Yakında doldurman öneriliyor.`}", "? t('fuelReminder.crit_desc', { r: estimate.estimatedRange })\n                    : t('fuelReminder.warn_desc', { p: estimate.estimatedRangePct })}");

fr = fr.replace("\n                İstasyon\n", "\n                {t('fuelReminder.station')}\n");
fr = fr.replace(">Yeterli Yakıt</span>", ">{t('fuelReminder.enough_fuel')}</span>");

fr = fr.replace("urgency={estimate.urgency}\n            />", "urgency={estimate.urgency}\n              t={t}\n            />");

fr = fr.replace("estimate.daysSinceLastFill === 0 ? 'Bugün'\n                  : estimate.daysSinceLastFill === 1 ? 'Dün'\n                    : `${estimate.daysSinceLastFill} gün önce`\n                : 'Kayıt yok'", "estimate.daysSinceLastFill === 0 ? t('fuelReminder.d_today')\n                  : estimate.daysSinceLastFill === 1 ? t('fuelReminder.d_yest')\n                    : t('fuelReminder.d_days', { d: estimate.daysSinceLastFill })\n                : t('fuelReminder.no_rec')");

fr = fr.replace("label=\"Son Dolum\"", "label={t('fuelReminder.last_fill')}");
fr = fr.replace("label=\"Son Dolumdan Km\"", "label={t('fuelReminder.km_since')}");
fr = fr.replace("label=\"Ort. Tüketim\"", "label={t('fuelReminder.avg_c')}");
fr = fr.replace("`${profile.avgConsumption} L/100km (manuel)`", "`${profile.avgConsumption} L/100km ${t('fuelReminder.manual')}`");

fr = fr.replace("label=\"Doldurma Önerisi\"", "label={t('fuelReminder.fill_rec')}");
fr = fr.replace("? `~${estimate.fillSuggestionKm} km sonra`\n                : 'Şimdi doldur!'", "? t('fuelReminder.after_km', { k: estimate.fillSuggestionKm })\n                : t('fuelReminder.fill_now')");

fr = fr.replace("const trendLabel = estimate?.trend === 'improving' ? 'İyileşiyor' :\n    estimate?.trend === 'worsening' ? 'Kötüleşiyor' :\n      estimate?.trend === 'stable' ? 'Sabit' : 'Yeterli veri yok';", "const trendLabel = estimate?.trend === 'improving' ? t('fuelReminder.tr_imp') :\n    estimate?.trend === 'worsening' ? t('fuelReminder.tr_wor') :\n      estimate?.trend === 'stable' ? t('fuelReminder.tr_stb') : t('fuelReminder.tr_no');");

fr = fr.replace(">Tüketim Trendi</p>", ">{t('fuelReminder.trend')}</p>");
fr = fr.replace("formatter={(v: number) => [`${v} L/100km`, 'Tüketim']}", "formatter={(v: number) => [`${v} L/100km`, t('fuelReminder.tt_val')]}");
fr = fr.replace(">--- 8 L/100km referans çizgisi</p>", ">{t('fuelReminder.ref_line', { v: 8 })}</p>");

fr = fr.replace(">Yakıt Tasarrufu İpuçları</p>", ">{t('fuelReminder.tips_title')}</p>");

const oldTips = `[\n              'Düzenli lastik basıncı kontrolü %3 yakıt tasarrufu sağlar.',\n              'Ani fren ve hızlanmadan kaçının — sabit hız daha az yakar.',\n              'Motor ısınınca yolculuk başlatmak soğuk çalışmadan daha verimli.',\n            ]`;
const newTips = `[t('fuelReminder.tip_1'), t('fuelReminder.tip_2'), t('fuelReminder.tip_3')]`;
fr = fr.replace(oldTips, newTips);

fr = fr.replace("\n              Yakıt Kaydı Ekle\n", "\n              {t('fuelReminder.add_rec')}\n");
fr = fr.replace("\n              İstasyon Bul\n", "\n              {t('fuelReminder.find_station')}\n");

fr = fr.replace("Menzil tahmini geçmiş yakıt kayıtlarından hesaplanır. Sürüş koşulları, trafik ve klima kullanımı gerçek menzili etkileyebilir.\n              Kesin sonuç için yakıt göstergenize bakın.", "{t('fuelReminder.disclaimer')}");
fr = fr.replace("Menzil tahmini geçmiş yakıt kayıtlarından hesaplanır. Sürüş koşulları, trafik ve klima kullanımı gerçek menzili etkileyebilir.\n                Kesin sonuç için yakıt göstergenize bakın.", "{t('fuelReminder.disclaimer')}");

fr = fr.replace(">Yakıt Verisi Yok</p>", ">{t('fuelReminder.no_data_title')}</p>");
fr = fr.replace(">\n            Tahmin yapabilmek için yakıt alımı kaydı ekle. Litre bilgisini girerek tüketim analizi başlar.\n          </p>", ">\n            {t('fuelReminder.no_data_desc')}\n          </p>");
fr = fr.replace("\n            İlk Yakıt Kaydını Ekle\n", "\n            {t('fuelReminder.first_rec')}\n");

fr = fr.replace("onClose={() => setShowSettings(false)}\n        />", "onClose={() => setShowSettings(false)}\n          t={t}\n        />");

fs.writeFileSync('pages/FuelReminder.tsx', fr);

console.log('DamageDetection and FuelReminder translated!');
